### ISSUE TITLE
[Backend] As a logged in user, I can logout from the application

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#14]
## Why

A user can logout from the application
 
## Who Benefits?

all users

**Comment by malparty** [comment]
@tyrro I see you would often write `everyone` in the `Who Benefits`. I would recommend to write `all users` instead. This way, when working on a `chore` you can also write `developers` or `dev team` (test automation does not directly provide benefits to the user, even if they indirectly help reduce bugs on the production app). 

In this specific task, I would even write "logged user", so that it's clear that any user not logged won't benefit (or need) this feature ;-)

**Comment by tyrro** [comment]
> I would recommend to write all users instead. This way, when working on a chore you can also write developers or dev team
>
Makes sense, I'd update every issues accordingly as I work along!
> In this specific task, I would even write "logged user"
>
Right, it's more specific, edited 👍
